### ISSUE TITLE
Why pin pydantic?

### ISSUE THREAD

**Issue by ferrine** [caniko/pydantic-numpy#13]
https://github.com/caniko/pydantic-numpy/blame/792e57e6434e1c9a087acd3704301bcada8992cd/pyproject.toml#L26

**Comment by ferrine** [comment]
for some reason, pylance does not recognize any type hints

**Comment by caniko** [comment]
Can you clarify the issue a bit more? I am afraid that this might be a `pydantic` issue or something missing on your end. The changes you have made in the PR shouldn't solve any issue with regard to `pylance`.

`>=3.0.0` requires Pydantic `>=2.0,<3.0` (equivalent to `^2.0`).

**Comment by ferrine** [comment]
I did not know ^2.0 pins properly

**Comment by ferrine** [comment]
The issue with pylance is separate, I discovered that one later

**Comment by ferrine** [comment]
I'll close that issue and will investigate the pylance behaviour separately
