### ISSUE TITLE
serializing/deserializing numpy types

### ISSUE THREAD

**Issue by rbavery** [caniko/pydantic-numpy#19]
Hello, I have a question about the tip in https://github.com/pydantic/pydantic-extra-types/issues/31#issuecomment-1817746747 (apologies again for my error!)

I took a look at and tried to use pydantic_numpy.typing to serialize numpy types. But it looks like the models are for numpy arrays (from different sources, paths or in memory np arrays).

https://github.com/caniko/pydantic-numpy/blob/trunk/pydantic_numpy/helper/annotation.py#L111

I'm actually only trying to serialize numpy types to json and read types back from json and validate them. Not do validation on the actual np arrays. Does pydantic_numpy support this?

The alternative I have tried is to define my own field validators, but with this I think I will need to make my own mapping between strings representing numpy types and np types. Using np.dtype with BaseModel results in a serialization error.

```
class TensorInfo(BaseModel):
    dtype: np.dtype = Field(...)
    shape: Union[Tuple[int, ...], List[int]] = Field(...)

    class Config:
        arbitrary_types_allowed = True


    @field_validator('dtype')
    def validate_dtype(cls, v):
        if not isinstance(v, np.dtype):
            raise ValueError(f'Expected np.dtype, received {type(v).__name__}')
        return v

    @field_validator('shape')
    def validate_shape(cls, v):
        if not isinstance(v, (tuple, list)):
            raise ValueError(f'Expected tuple or list for shape, received {type(v).__name__}')
        return tuple(v)
```

**Comment by caniko** [comment]
This currently works for `int` and `float` based types, I am implementing it for `timedelta64` and `datetime64`. Will make PR soon

**Comment by caniko** [comment]
Update to `4.1.0` for this feature :rocket:

**Comment by caniko** [comment]
@rbavery did you try to use it?

**Comment by rbavery** [comment]
Hi @caniko I did, thanks for checking in. I took a look at the PR you submitted but it's not clear to me how this enables only serializing the types to json, leaving out the numpy array. 

https://github.com/caniko/pydantic-numpy/pull/20/files#diff-35ff13acb747a8fc01e3dbee84763b158eba7f8b0d7d43741e626f41ba734a32R133

for example, I'm looking to serialize shape and type information, but not the arrays themselves

```
{
  "signatures": {
    "inputs": [
      {
        "name": "input_tensor",
        "dtype": "float32",
        "shape": [
          -1,
          13,
          64,
          64
        ]
      }
    ],
    "outputs": [
      {
        "name": "output_tensor",
        "dtype": "float32",
        "shape": [
          -1,
          10
        ]
      }
    ],
    "params": null
  },
  "artifact": {
    "path": "s3://path/model.pt",
    "additional_files": null
  },
  "id": "2471b71746824665be40dce05a88906f",
  "class_map": {
    "class_to_label_id": {
      "Annual Crop": 0,
      "Forest": 1,
      "Herbaceous Vegetation": 2,
      "Highway": 3,
      "Industrial Buildings": 4,
      "Pasture": 5,
      "Permanent Crop": 6,
      "Residential Buildings": 7,
      "River": 8,
      "SeaLake": 9
    }
  },
  "runtime_config": null,
  "name": "eurosat",
  "ml_model_type": null,
  "ml_model_processor_type": "cpu",
  "ml_model_learning_approach": null,
  "ml_model_prediction_type": null,
  "ml_model_architecture": null
}
```

this is what I have and it is not a lot of code and is working so I might stick with it

```
class TensorSignature(BaseModel):
    """Tensor metadata, including the dtype (int8, float32, etc) and the tensor shape.
    """
    name: Optional[str] = None
    dtype: np.dtype = Field(...)
    shape: Tuple[int, ...] | List[int] = Field(...)

    class Config:
        arbitrary_types_allowed = True
        json_encoders = {
            np.dtype: lambda dtype: dtype.name,
        }

    @field_validator('dtype', mode="before")
    @classmethod
    def convert_dtype(cls, v):
        if isinstance(v, str):
            v = np.dtype(v)
        elif not isinstance(v, np.dtype):
            raise ValueError(f'Expected np.dtype, received {type(v).__name__}')
        return v

    @field_validator('shape')
    @classmethod
    def validate_shape(cls, v):
        if not isinstance(v, (tuple, list)):
            raise ValueError(f'Expected tuple or list for shape, received {type(v).__name__}')
        return list(v)
```

**Comment by caniko** [comment]
You wrote this:

> I'm actually only trying to serialize numpy types to json and read types back from json and validate them.

Now you say this:

> for example, I'm looking to serialize shape and type information, but not the arrays themselves

The revised request does not fit the definition of serialization/deserialization of numpy arrays; rather their type and shape. You don't need `pydantic-numpy`, and you should stick with your current implementation.

Something that could be implemented in `pydantic-numpy` is exact shape validation; nonetheless, this is not something you need because you never store the data itself in the model.
