### ISSUE TITLE
cannot import name 'ModelField' from 'pydantic.fields'

### ISSUE THREAD

**Issue by epifanio** [caniko/pydantic-numpy#2]
the following import::
[`from pydantic.fields import ModelField`](https://github.com/cheind/pydantic-numpy/blob/main/pydantic_numpy/dtype.py#L9)

trows an exception when using latest pydantic

```
>>> from pydantic.fields import ModelField
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ModelField' from 'pydantic.fields' (/home/epinux/mambaforge/envs/fastapi/lib/python3.10/site-packages/pydantic/fields.py)
```

confirmed in: https://github.com/pydantic/pydantic/issues/6701   `ModelField` is no longer available

**Comment by caniko** [comment]
Hello, you seem to be on Pydantic V2. I am in the process of migrating to V2, please give me a couple of days.

I may suggest Pydantic <2.0 if it is urgent :)

**Comment by epifanio** [comment]
Hi, thanks for your reply. Yes that is correct, which implies a downgrade for `fastapi`as well, the combination I found that works in my use case is:

```
"pydantic==1.10.8"
"fastapi==0.96.0"
```

**Comment by caniko** [comment]
Pydantic V2 is supported now! Please consider starring the repository! Thanks
