### ISSUE TITLE
Multiple levels of NumpyModel and __eq__

### ISSUE THREAD

**Issue by alonks1234** [caniko/pydantic-numpy#26]
It seems like __eq__ works for up to levels of composition, but at 3 there is a bug where the __eq__ operation ends up directly comparing numpy arrays:

```
        class A(NumpyModel):
            a: pnd.NpNDArray = Field(frozen=True)
        
        class B(NumpyModel):
            a: A = Field(frozen=True)
        
        class C(NumpyModel):
            b: B = Field(frozen=True)
        
        a = A(a=np.zeros((10, 10)))
        b = B(a=a)
        c = C(b=b)

        other_c = C(b=B(a=A(a=np.zeros((10, 10)))))
        assert c == other_c
```

I suspect this is because the following function:

```
    def _dump_numpy_split_dict(self) -> tuple[dict, dict]:
        ndarray_field_to_array = {}
        other_field_to_value = {}

        for k, v in self.model_dump(exclude_unset=True).items():
            if isinstance(v, np.ndarray):
                ndarray_field_to_array[k] = v
            else:
                other_field_to_value[k] = v

        return ndarray_field_to_array, other_field_to_value
```

Uses .model_dump() at the top level, and instead needs to recursively dump models if it contains other NumpyModels

**Comment by caniko** [comment]
There is currently no support for nested `NumpyModel`s, it didn't cross my mind during its design (it should've).

You are free to create a PR to solve #25 and this issue, and I will review it.

**Comment by caniko** [comment]
We need to discuss where to store the data of the nested `NumpyModels` upon `dump()` call; the `load()` logic should be implemented similarly, of course.

My initial design proposal is to dump the data in a directory with the respective field name.

**Comment by alonks1234** [comment]
The directory structure matching the structure of the models is pretty intuitive to me.

**Comment by caniko** [comment]
Good; however, it could've been a disaster of a PR if we didn't make this clear before you spent your precious time. Godspeed.

**Comment by alonks1234** [comment]
https://github.com/caniko/pydantic-numpy/pull/27

Threw together a quick version of this.
