### ISSUE TITLE
Factory methods for custom JSON serializers

### ISSUE THREAD

**Issue by futurewasfree** [caniko/pydantic-numpy#28]
Hello again! :)

Just wanted to ask for advice, what would be the best way to use custom json serializer with pydantic_numpy models?
Let's say that for whatever reason you want to use `NumpyDataDict` and instead use simple `arr.tolist()` (yes, losing information about `data_type` and assuming float). 
As it is now it's only possible if you redefine custom version `NpArrayPydanticAnnotation` core_schema serialization defined inside. 
Alternatively, will it be a good idea to add something like this to factory method?

Would be happy for any pointers/advice!

WIth kind regards,
Sergei.

**Comment by caniko** [comment]
Hello!

If you could provide a bit more detail about your specific needs or the background of your project/request, it would really help in giving you the most relevant advice. It's totally understandable that sometimes standard solutions in third-party packages might not perfectly align with your vision. That's one of the reasons why factory methods are so valuable – they offer that much-needed flexibility.

However, it's also true that you can't have a factory method for everything. Finding the right balance is key. About your thoughts on serialization, shifting away from the current method might affect the predictability and consistency you're enjoying now - as you are leaving the data typing inferencing to NumPy. It's always a bit of a trade-off.

I'm definitely open to exploring the idea of adding a factory method to the JSON serializer, although I would be contributing more in an advisory or review role.

**Comment by futurewasfree** [comment]
Good morning!

Just to give more context: let's say you have certain established data structure (i.e. calibration data) stored as json dict. And you want to migrate it into pydantic model (with the use of pydantic_numpy) when you work with it internally, since it adds a lot of convenience and type safety. In this case you can not change format (?) or you could but with a lot of efforts across the stack. So this extra nestedness of `NumpyDataDict` is sort of on the way..

As I've said I'm totally fine with a custom factory function on my side, was just wondering if this could be a more common use case, when you really want 1-to-1 correspondence between field name with numpy array and json list in a dict.
I could totally see that it's domain and application specific, but where I work now `timedelta` in numpy array is quite rare.

Another little question that I have is about flag `when_used`:  `json` over `always`. What's the main idea behind that? Performance reasons, I guess?

Cheers!

**Comment by caniko** [comment]
> Another little question that I have is about flag when_used: json over always. What's the main idea behind that? Performance reasons, I guess?

It has been a while, and definitely not related to any voluntary performance optimization. Would you use `json` instead? Why?

**Back to the main issue**

This makes total sense; however, is the nesting much of a hindrance? You could just remove it from the JSON with a simple script. This is just a comment on how I would do it; not saying that your design is wrong.

Feel free to add a JSON serializer factory method, where the current method is the default.

**Comment by futurewasfree** [comment]
Re: `when_used`. This is how it is in the code, right now:
```
 serialization=core_schema.plain_serializer_function_ser_schema(
                _serialize_numpy_array_to_data_dict, when_used="json"
            ),
```
I would rather use `when_used=always`, which is default I believe and hence my question.

Re: main issue. Just to understand your suggestion better, on removal it from JSON with simple script. Do you suggest to post process and rewrite json coming from pydantic's `model_dump_json()`? 

I'll think on how to add it to factory method, on which level. Depends also on that `when_used` flag, if we could change it.

**Comment by caniko** [comment]
I am prepared to discuss `when_used`, could you open another issue outlining the reasoning to use `always` over `json`? Currently considering `json-unless-none` over `json`.

> Re: main issue. Just to understand your suggestion better, on removal it from JSON with simple script. Do you suggest to post process and rewrite json coming from pydantic's model_dump_json()?

Not exactly. If I ever needed to get rid of the data dict in the JSON I would remove it at that time; otherwise, we would have to delete information from our data store (the data type):

1. Dump to JSON
2. Store the JSON
3. Read the JSON
4. Parse the JSON
5. Extract array data from data dict (discard data type)

I would do it your way when we would be removing the data dict anyway.

**Comment by futurewasfree** [comment]
Thank you for your answer! I think I've understood your point here. I'll open another one on `when_used`

**Comment by caniko** [comment]
Added with #32

**Comment by futurewasfree** [comment]
awesome-o!
