### ISSUE TITLE
Incompatibilty with NumPy 2

### ISSUE THREAD

**Issue by NikosAlexandris** [caniko/pydantic-numpy#50]
I am in need of the magix in pydantic-numpy. The following combination of versions works :

``` bash
uv pip install netCDF4==1.6.5 numpy==1.26.4 pydantic-numpy==5
```
Upgrading to
``` bash
numpy              2.1.2
pydantic-numpy     6.0.0
netcdf4            1.7.1.post2
```
breaks my program, it returns
``` bash
Segmentation fault (core dumped)
```

I have a quite complex program and I'd need some time to create a minimal non-working example. But, is the latest version of pydantic-numpy at all compatible with NumPy 2 ?

**Comment by caniko** [comment]
I haven't ran the tests for v2.1 yet, but they ran fine with v2.0. Will run them for v2.1; let's see if they fail.

**Comment by caniko** [comment]
All tests are passing unfortunately

**Comment by caniko** [comment]
Closing. I am open to revisiting the problem you are having just not under this issue, this is too vague! You may refer to this issue if you want.

**Comment by caniko** [comment]
I uploaded a new version of the package with bumped dependencies, might be worth a shot.

**Comment by NikosAlexandris** [comment]
I have no idea what the problem is exactly with netCDF4. Ditching it in favor of https://github.com/h5netcdf/h5netcdf/tree/v1.4.0 along withNumPy 2.1.2, `pydantic-numpy` 6.0.1 just works -- set aside that all runs faster by quite some hundreds of milliseconds !
