### ISSUE TITLE
Validation doesn't seem to work according to the documented usage example

### ISSUE THREAD

**Issue by NellyWhads** [caniko/pydantic-numpy#52]
Here's a simple run of the library in a python 3.10 environment:
1. clone this repo
2. `poetry install --all-extras`
3. make a python notebook and point it to the appropriate kernel
4. Run this example

```python
import numpy as np
from pydantic import BaseModel

import pydantic_numpy.typing as pnd
from pydantic_numpy import np_array_pydantic_annotated_typing

class MyModel(BaseModel):
    k: np_array_pydantic_annotated_typing(data_type=np.uint8, dimensions=1)
    k2: pnd.NpNDArrayInt8

instance = MyModel(k=np.array([1,2,3]).astype(np.int32), k2=np.arange(12).reshape((3, 4)).astype(np.float32))
```

The expected behaviour is for validation to fail, however, it passes.

**Comment by caniko** [comment]
It passes because the type is cast to the correct `dtype`.

**Comment by caniko** [comment]
If you want to be strict use `import pydantic_numpy.typing.strict_data_type`
