### ISSUE TITLE
numpy does not have float128 on windows

### ISSUE THREAD

**Issue by wlwatkins** [caniko/pydantic-numpy#6]
On windows I get "AttributeError: module 'numpy' has no attribute 'float128'" which is due to the fact that you are implementing float128, and even complexe256. though I know the former is not available for windows. https://github.com/winpython/winpython/issues/613#issuecomment-380121523 is there a way to put some flags so that if it is on windows in stops at float64?

**Comment by caniko** [comment]
Fixed with #7
